apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pep-pvc
  namespace: wielder-services
  labels: 
    app: pep
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 200Mi
  storageClassName: pep-storage