apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pep-pv
spec: 
  capacity: 
    storage: 200Mi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pep-storage
  local: 
    path: /Users/gideonbar/dev/data/micros/perl/pep
  nodeAffinity: 
    required: 
      nodeSelectorTerms: 
        - 
          matchExpressions: 
            - 
              key: kubernetes.io/hostname
              operator: In
              values: 
                - docker-desktop